Don't set juju snap channel and pip constraints
openstack-charmers/zosci-config pull request #343
Opened 2024-06-27 19:11 UTC by sabaini

Use juju 2.9 in gate as we don't support newer Juju with Zaza yet

Depends-On: openstack-charmers/zaza#652

2024-06-28 13:52 UTC, ajkavanagh requested changes
This is a revert effectively.

2024-06-28 13:52 UTC, ajkavanagh commented on zuul.d/jobs.yaml
> +      # pip_constraints_url: 'https://raw.githubusercontent.com/openstack-charmers/zaza-openstack-tests/master/constraints/constraints-noble.txt'
For noble, we're transitioning to juju 3.5/stable, and moving off from 2.9; thus we don't really want to revert this change.

2024-06-28 13:53 UTC, ajkavanagh commented
> Use juju 2.9 in gate as we don't support newer Juju with Zaza yet

> Depends-On: https://github.com/openstack-charmers/zaza/pull/652

We probably want to look at this again.  We need to move forward and use Juju 3.x for noble.

2024-07-24 09:05 UTC, sabaini commented
Closing -- we're now running juju3 with zaza

2024-07-24 09:05 UTC, closed without merging